version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .envs/.django

    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis

  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker --loglevel=INFO
    env_file: .envs/.django
    depends_on:
      - db
      - redis
      - web
