# Generated by Django 4.1.2 on 2022-11-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="place_of_payment",
        ),
    ]
