# Generated by Django 4.1.2 on 2022-10-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pin",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="is email verified"),
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
        migrations.DeleteModel(
            name="Pin",
        ),
    ]
